"""empty message

Revision ID: ba448a6797b7
Revises: 2a55268b41ee
Create Date: 2022-06-19 16:49:19.241532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba448a6797b7'
down_revision = '2a55268b41ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('img_path', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('img_path')
        batch_op.drop_column('link')

    # ### end Alembic commands ###
